name: Randall Cleveland
favicon: null
layout_spectrum: 0.94836
typography_spectrum: 0.29703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191f2b'
    - '#5e786b'
    - '#f5e3a3'
    - '#dc8e5d'
    - '#fefdff'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
