name: Randall Cleveland
favicon: null
layout_spectrum: 0.92126
typography_spectrum: 0.29342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cab9af'
    - '#2c2628'
    - '#2388b2'
    - '#8e7b7f'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
